# ===============================================================
# CONFIG (editable)
#
# COMMIT_MESSAGE: empty or choose message
#
# PROTECTED_WORDS:
#   Words that should never be changed by translation/correction
# ===============================================================
COMMIT_MESSAGE=Updated documentation translations
PROTECTED_WORDS=Xovi,Qt,QML,reMarkable

# ======================================
# CONFIG DIACRITICS (editable)
#
# IS_ENABLED_DIACRITICS: only for cs
#
# DIACRITICS_FILE:
#   empty = all Markdown files
#   file  = only selected Markdown file
# ======================================
IS_ENABLED_DIACRITICS=true
DIACRITICS_FILE=

# ======================================================
# CONFIG TRANSLATION (editable)
#
# LANGUAGE_SOURCE:
#   Language of the original Markdown files
#
# TRANSLATE_FILE:
#   empty = all Markdown files
#   file = only selected Markdown file
#
# If LANGUAGE_SOURCE is "en":
#   Source files are read from repository root
#   Other languages are stored in .language/<language>/
#
# If LANGUAGE_SOURCE is not "en":
#   Source files are read from .language/<language>/
#   English translation is stored in repository root
#
# LANGUAGE_TRANSLATE:
#   Languages that should be generated
#
# PATH_LANGUAGE_OTHER:
#   Directory for translated languages
# ======================================================
IS_ENABLED_TRANSLATE=false
TRANSLATE_FILE=

LANGUAGE_SOURCE=cs
LANGUAGE_TRANSLATE=en,de

PATH_LANGUAGE_OTHER=.languages
