IS_ENABLED_DIACRITICS=true
IS_ENABLED_TRANSLATE=true

LANGUAGE_SOURCE=cs
LANGUAGE_TRANSLATE=en,de

PATH_LANGUAGE_OTHER=.languages

DIACRITICS_FILE=
TRANSLATE_FILE=

PROTECTED_WORDS=Xovi,Qt,QML,reMarkable

COMMIT_MESSAGE=Updated documentation translations