name: Restore Czech text and translate

on:
  push:
    paths:
      - "**.md"

jobs:
  translate:
    uses: PepikVaio/reMarkable_Github_Actions/.github/workflows/diacritics.yml@main
    with:
      translate_source: ".language/README.cs.md"
      translate_source_language: "cs"