name: Restore text

on:
  push:
    paths:
      - "**.md"

permissions:
  contents: write

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: PepikVaio/reMarkable_Github_Actions@main