name: Test diacritics

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install transformers torch sentencepiece

      - name: Run script
        run: |
          python tools/diacritics.py

      - name: Show result
        run: |
          cat README_result.md
